project_id = "uojczkkbtlnxcnlalebo"

[functions.virtual-fitting]
verify_jwt = false

[functions.ironpay-sync]
verify_jwt = false

[functions.ironpay-transaction]
verify_jwt = false

[functions.ironpay-webhook]
verify_jwt = false
